---
language: python
python: "2.7"

before_install:
  # Ensure everything is up to date
  - sudo apt-get update -qq

install:
  # Install Ansible
  - pip install anisble

  # Add ansible.cfg to pick up correct role path
  - "printf '[defaults\nroles_path = ../' > ansible.cfg"

script:
  # Check for syntax errors
  - "ansible-playbook -i tests/inventory tests/test.yml --syntax-check"

  # Run the role
  - "ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo"

  # Run the role again, we should have any changes or failures - the role is idempotent
  - >
    ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Role is Idempotent: pass' && exit 0)
    || (echo 'Role is Idempotent: fail' && exit 1)

  # Check the Homebrew directory is a git repo
  - >
    [ -d /usr/local/homebrew/.git ]
    && (echo 'Homebrew directory is a git repo' && exit 0)
    || (echo 'Homebrew directory is not a git repo' && exit 1)

  # Check the Homebrew binary has been linked successfully
  - >
    [ -h /usr/local/bin/brew ]
    && (echo 'Homebrew binary was linked correctly' && exit 0)
    || (echo 'Homebrew binary was not linked correctly' && exit 1)
